-- Wizard: СУПЕРОБНОВЛЕНИЕ БД (запусти ВЕСЬ скрипт в Supabase -> SQL Editor -> Run)

-- 1) Заказы: добавить колонку email (почта покупателя)
alter table public.orders add column if not exists email text;

-- 2) Ключи: срок по ДНЯМ (вместо месяцев)
alter table public.app_keys add column if not exists days integer;

-- 3) Таблица ЛОГОВ (кто заходил, когда, в какой вкладке)
create table if not exists public.logs (
  id bigint generated by default as identity primary key,
  nick text,
  event text,
  detail text,
  at bigint
);
alter table public.logs enable row level security;
create policy "anon_all_logs" on public.logs for all using (true) with check (true);
alter table public.logs replica identity full;

-- 4) Таблицы на первичное создание, если их ещё нет
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  nick text not null,
  email text,
  plan text,
  months integer,
  forever boolean default false,
  amount integer,
  promo text,
  status text default 'checking',
  created_at bigint,
  confirmed_at bigint
);
alter table public.orders enable row level security;
create policy "anon_all_orders" on public.orders for all using (true) with check (true);
alter table public.orders replica identity full;

-- Настройки бОльше НЕ нужны (QR лежит в репозитории). Скипни таблицу settings, если появилась — можно удалить:
drop table if exists public.settings;