-- Wizard: таблицы orders и settings
-- Выполнить в Supabase Dashboard -> SQL Editor -> паста -> Run
-- Проверить: CLOUD : Orders (входит App_G2)

create table if not exists public.settings (
  id bigint primary key default 1,
  sbp_qr_url text,
  sbp_req text,
  constraint settings_singleton check (id = 1)
);
alter table public.settings enable row level security;
create policy "anon_all_settings" on public.settings for all using (true) with check (true);
alter table public.settings replica identity full;

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  nick text not null,
  plan text,
  months integer,
  forever boolean default false,
  amount integer,
  promo text,
  status text default 'checking',
  created_at bigint,
  confirmed_at bigint
);
alter table public.orders enable row level security;
create policy "anon_all_orders" on public.orders for all using (true) with check (true);
alter table public.orders replica identity full;